Repository canonical/cn.ubuntu.com, pull requests merged in 2018-09, with the labels that each got.

#230 Update to standard GTM
  templates/templates/base.html
Labels: Review: Code +1

#233 Site updates
  static/img/about/products-hero-container.jpg
  templates/about/index.html
  templates/cloud/index.html
  templates/contact/index.html
  templates/containers/index.html
  templates/desktop/index.html
  templates/index.html
  templates/internet-of-things/index.html
  templates/server/index.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#234 Add CircleCI workflow
  .circleci/config.yml
  .travis.yml
  package.json
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#235 Make footer date dynamic
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1
