Repository canonical/cn.ubuntu.com, pull requests merged in 2018-03, with the labels that each got.

#189 Update run script to v2.7.1
  .bowerrc
  .gitignore
  .sass-lint.yml
  README.md
  bower.json
  package.json
  run
  static/global-nav
  static/sass/styles.scss
  templates/contact/index.html
  templates/desktop/index.html
  templates/download/index.html
  templates/internet-of-things/index.html
  templates/news/2015/02/06/bqs-new-aquaris-e4-5-ubuntu-edition-the-smartphone-that-puts-content-and-services-at-your-fingertips.html
  templates/server/index.html
  templates/templates/base.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#190 Add docker file
  Dockerfile
  requirements.txt
  webapp/wsgi.py
Labels: Review: Code needed

#191 Bump global nav version
  package.json
  yarn.lock
Labels: Review: Code +1

#192 Update download links
  templates/download/index.html
Labels: Review: Code needed, Review: QA needed

#193 Remove kylin download links
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1

#202 Update hero
  static/sass/custom/_ubuntu_intro.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#196 Use talisker in production Dockerfile
  Dockerfile
Labels: Review: Code +1, Review: QA +1
