Repository canonical/cn.ubuntu.com, pull requests merged in 2019-10, with the labels that each got.

#347 Rearrange head tag for performance
  .gitignore
  templates/templates/base.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#348 19.10 release
  templates/download/index.html
  templates/server/index.html
Labels: Review: Code +1

#350 Reduce docker image size
  .dockerignore
  Dockerfile
Labels: Review: Code +1, Review: QA +1
