Repository canonical/cn.ubuntu.com, pull requests merged in 2019-01, with the labels that each got.

#273 Remove unused dependencies
  requirements.txt
  templates/contact/index.html
  templates/desktop/index.html
  templates/index.html
  templates/internet-of-things/index.html
  templates/news/2015/05/21/meizu-ubuntu.html
  templates/news/2015/07/03/asus-china-ubuntu-kylin.html
  templates/news/2015/10/22/1510-release.html
  templates/news/2015/12/18/china-mobile-conference.html
  templates/news/2016/04/07/ubuntu-on-windows.html
  templates/news/2016/04/08/phone-ota10.html
  templates/news/2016/04/21/ubuntu-kylin-1604-lts.html
  templates/news/2016/04/25/ubuntu-1604-released.html
  templates/news/2016/06/15/ubuntu-core-qnap-nas.html
  templates/news/2016/11/18/ubuntu-core-16-launches.html
  templates/news/2016/12/19/ubuntu-core-iot.html
  templates/news/2017/03/16/orange-pi-snap-store.html
  templates/server/index.html
  templates/takeovers/_kylin.html
  templates/templates/404.html
  templates/templates/500.html
  templates/templates/base.html
  templates/templates/header.html
  webapp/settings.py
  webapp/urls.py
  webapp/views.py
  webapp/wsgi.py
Labels: Review: Code +1, Review: QA +1

#274 Fix legal footer link
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#251 Update the navigation to match the latest design
  static/sass/_patterns_navigation.scss
  static/sass/_settings_colors.scss
  static/sass/styles.scss
  templates/templates/header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#275 Fix bad merge
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#276 Fix navigation with redirects
  .dockerignore
  redirects.yaml
  requirements.txt
  webapp/settings.py
  webapp/urls.py
Labels: Review: Code needed, Review: QA needed

#282 Renovate: group minor updates
  renovate.json
Labels: Review: Code +1, Review: QA +1

#285 Add "test-site" CI step
  .circleci/config.yml
Labels: Review: Code needed, Review: QA needed

#286 Indent Canonical logo in global nav
  static/sass/styles.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1
