Repository canonical/cn.ubuntu.com, pull requests merged in 2019-04, with the labels that each got.

#303 Implement blog on cn.ubuntu.com
  requirements.txt
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_blog-list.scss
  static/sass/_pattern_blog-post.scss
  static/sass/_utility_crop.scss
  static/sass/styles.scss
  templates/blog/article.html
  templates/blog/blog-card.html
  templates/blog/featured-posts.html
  templates/blog/index.html
  webapp/settings.py
  webapp/templatetags/__init__.py
  webapp/urls.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#305 Includes the blog into the navbar
  templates/templates/header.html
Labels: Review: Code needed, Review: QA +1

#308 Sets the active navigation link color to orange
  static/sass/_settings_colors.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#309 Checks for blog as path root in blog item
  templates/templates/header.html
Labels: Review: Code +1, Review: QA +1

#314 Use re path
  .gitignore
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#318 Update the 19.04 server features copy
  templates/server/index.html
Labels: Review: Code +1

#317 Removes duplicated ID and unnecessary class
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1

#315 Adds JavaScript build pipeline and updates global nav
  .eslintrc.js
  .gitignore
  package.json
  static/dist/latest-news.js
  static/js/global-nav.js
  templates/templates/base.html
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#316 Latest news widget
  requirements.txt
  static/js/latest-news.js
  templates/index.html
  templates/shared/_latest-news.html
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#320 Updates latest news to provide 4 normal articles in case no spotlight…
  requirements.txt
  static/js/latest-news.js
  templates/shared/_latest-news.html
Labels: Review: Code +1, Review: QA +1

#323 Translates english strings
  static/js/latest-news.js
  templates/blog/article.html
  templates/shared/_latest-news.html
Labels: Review: Code +1

#324 Updates blog module to 1.3.5 to fix 404 on article pages
  requirements.txt
Labels: Review: QA +1
