Repository canonical/cn.ubuntu.com, pull requests merged in 2020-09, with the labels that each got.

#431 Update blog version to 6.2.3
  requirements.txt
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#432 Add new webinar takeover and engage page
  templates/engage/ubuntu-tech-live-episode-2.html
  templates/index.html
  templates/takeovers/_iot-webinar_session_2.html
Labels: Review: Code +1, Review: QA +1

#433 Update flask-base
  .github/workflows/pr.yaml
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#434 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1
