Repository canonical/cn.ubuntu.com, pull requests merged in 2021-03, with the labels that each got.

#497 Add redirect for /iot to /internet-of-things
  redirects.yaml
Labels: Review: Code needed, Review: QA needed

#498 Make primary_cta optional, remove old takeovers
  templates/engage/base_engage.html
  templates/engage/index.html
  templates/engage/shared/_engage_form.html
  templates/engage/thank-you.html
  templates/engage/ubuntu-tech-live-episode-5.html
  templates/index.html
  templates/takeovers/_active-directory-takeover.html
  templates/takeovers/_desktop-developer-takeover.html
  templates/takeovers/_hackathon.html
  templates/takeovers/_iot-webinar_session_1.html
  templates/takeovers/_iot-webinar_session_2.html
  templates/takeovers/_iot-webinar_session_3.html
  templates/takeovers/_iot-webinar_session_4.html
  templates/takeovers/_iot-webinar_session_5.html
  templates/takeovers/_kylin.html
  templates/takeovers/_openstack-ussuri.html
  templates/takeovers/_redhat-openstack.html
  templates/takeovers/_template.html
  templates/takeovers/_vmware-to-charmed-openstack.html
  templates/takeovers/_xdf-mass-case-study.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#496 Add secondary nav and new /internet-of-things/core page
  static/sass/_pattern_core.scss
  static/sass/_pattern_strip.scss
  static/sass/_patterns_navigation.scss
  static/sass/styles.scss
  templates/internet-of-things/core.html
  templates/internet-of-things/index.html
  templates/internet-of-things/secondary-nav.html
Labels: Review: Code +1, Review: QA +1

#502 Revert linkchecker to 18.04
  .github/workflows/linkchecker.yaml
Labels: Review: Code +1

#506 Remove Tenser dependency
  package.json
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#507 Make linkchecker ignore blog
  .github/workflows/linkchecker.yaml
Labels: Review: Code +1

#508 Fix tutorial 404 link
  templates/cloud/index.html
Labels: Review: Code needed
