Repository canonical/cn.ubuntu.com, pull requests merged in 2021-02, with the labels that each got.

#475 Engage pages and takeovers
  .stylelintrc
  Dockerfile
  package.json
  requirements.txt
  static/dist/latest-news.js
  static/js/third-party/serialize.js
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_strip.scss
  static/sass/_pattern_takeovers.scss
  static/sass/_utility_crop.scss
  static/sass/custom/_ubuntu_intro.scss
  static/sass/styles.scss
  templates/engage/base_engage.html
  templates/engage/index.html
  templates/engage/microsoft-active-directory.html
  templates/engage/openstack-ussuri-webinar.html
  templates/engage/redhat-openstack-comparison-whitepaper.html
  templates/engage/robot-operating-system-choice-cn.html
  templates/engage/shared/_article-card.html
  templates/engage/shared/_base_engage_markdown.html
  templates/engage/shared/_engage_form.html
  templates/engage/thank-you.html
  templates/engage/thank_you.html
  templates/engage/thank_you_ad.html
  templates/engage/thank_you_dd.html
  templates/engage/ubuntu-tech-live-episode-1.html
  templates/engage/ubuntu-tech-live-episode-2.html
  templates/engage/ubuntu-tech-live-episode-3.html
  templates/engage/ubuntu-tech-live-episode-4.html
  templates/engage/uc18wb.html
  templates/engage/vmware-to-openstack.html
  templates/engage/xdf-maas-ebook.html
  templates/index.html
  templates/takeovers/_template.html
  templates/takeovers/index.html
  webapp/app.py
  webapp/views.py
  yarn.lock
Labels: Review: Code +1 (with changes), Review: Marketing +1, Review: QA +1

#483 Update releases.yaml file and download page for 20.04.2 LTS
  releases.yaml
  templates/download/index.html
  templates/download/thank-you/index.html
Labels: Review: Code +1, Review: QA +1

#485 Fix form cta and add default
  templates/engage/base_engage.html
  templates/engage/shared/_engage_form.html
Labels: Review: Code needed, Review: QA needed

#488 Update index.html
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1
