Repository canonical/cn.ubuntu.com, pull requests merged in 2025-04, with the labels that each got.

#747 add link checker GH action
  .github/workflows/live-links.yml
  .github/workflows/pr.yaml
Labels: Review: Code +1 (with changes)

#748 Adjust live-links GH action configuration
  .github/workflows/live-links.yml
Labels: Review: Code +1

#749 WD-20398 Dev - Create [cn.ubuntu.com/microcloud]
  templates/microcloud/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1
