Repository canonical/cn.ubuntu.com, pull requests merged in 2025-05, with the labels that each got.

#752 fix: Failing links on homepage
  .github/workflows/live-links.yml
  templates/index.html
Labels: Review: QA +1, Review: Code +1

#753 chore: Ignore 401 error on linkchecker
  .github/workflows/live-links.yml
Labels: Review: Code +1

#754 fix: Use an updated flow for linkchecker
  .github/workflows/linkchecker.yaml
Labels: Review: Code +1

#750 Built certified hardware page
  requirements.txt
  static/sass/custom/_certified-testing-list.scss
  static/sass/styles.scss
  templates/certified/index.html
  templates/desktop/developers.html
  templates/desktop/organisations.html
  templates/desktop/partners.html
  templates/download/desktop.html
  templates/download/iot/index.html
  templates/internet-of-things/secondary-nav.html
  templates/kubernetes/index.html
  templates/macros/_vf_tiered-list.jinja
  templates/support/index.html
  templates/templates/base.html
  templates/templates/header.html
  yarn.lock
Labels: Feature 🎁, Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#758 Delete .github/workflows/linkchecker.yaml as it is not used anymore
  .github/workflows/linkchecker.yaml
Labels: Review: Code +1
